# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec9b7dc4ae659a4f9d9413c993072fcfc51954b769ce951a1f0a7a2c3b43dbc93120dd8300e3bda77657a08957f2389a6c122f8f884989670bdc0bd70ed2bb3

test:
  secret_key_base: de8ef89b784da92a0e8e5a65ef7f762b70624d2bdc21860df82bf20582e921e21a0769114d48914b9426d13e43b18c162968b1a77f6ded5ddd2ffe474055b1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
